# Generated by Django 5.1.5 on 2025-07-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0013_skincondition_page_prevention_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('remedies', 'Natural Remedies'), ('prevention', 'Prevention Tips'), ('ingredients', 'Ingredient Spotlights')], max_length=50)),
                ('featured_image', models.ImageField(upload_to='articles/')),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
