# Generated by Django 5.1.5 on 2025-07-12 05:01 (This timestamp will be YOUR generated timestamp)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0014_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.IntegerField(default=5),
        ),
        # THIS IS THE CRITICAL CHANGE: Use RunSQL for content field type conversion
        migrations.RunSQL(
            sql="ALTER TABLE predictor_article ALTER COLUMN content TYPE jsonb USING (CASE WHEN content = '' THEN '{}'::jsonb WHEN content IS NULL THEN NULL ELSE jsonb_build_object('sections', jsonb_build_array(jsonb_build_object('type', 'paragraph', 'text', content))) END);",
            reverse_sql="ALTER TABLE predictor_article ALTER COLUMN content TYPE text USING (CASE WHEN content IS NULL THEN NULL WHEN jsonb_typeof(content) = 'object' AND content ? 'sections' THEN content->'sections'->0->>'text' ELSE '' END);"
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]