# Generated by Django 5.1.5 on 2025-07-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0015_alter_article_options_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
