# Generated by Django 5.2.4 on 2025-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0016_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('remedies', 'DIY Beauty Lab'), ('prevention', 'Holistic Skin Wisdom'), ('ingredients', "Nature's Pharmacy"), ('skin-myths', 'Skin Secrets')], max_length=50),
        ),
    ]
