# Generated by Django 5.2.4 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0017_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('remedies', 'DIY Beauty Lab'), ('prevention', 'Holistic Skin Wisdom'), ('ingredients', "Nature's Pharmacy"), ('secret', 'Skin Secrets')], max_length=50),
        ),
    ]
