# Generated by Django 5.2.4 on 2025-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0018_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(max_length=600),
        ),
    ]
