# Generated by Django 5.1.5 on 2025-12-02 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0019_alter_article_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='approach',
            field=models.CharField(choices=[('ayurvedic', 'Ayurvedic'), ('western', 'Western Home Care'), ('herbal', 'Herbal Only')], default='herbal', max_length=20),
        ),
        migrations.AddField(
            model_name='remedy',
            name='safety_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('caution', 'Use with caution'), ('avoid_pregnancy', 'Avoid during pregnancy')], default='safe', max_length=20),
        ),
        migrations.AddField(
            model_name='remedy',
            name='scientific_evidence',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='remedy',
            name='traditional_evidence',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='FollowUpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('symptom_key', models.CharField(max_length=100)),
                ('why_this_question', models.TextField(help_text='Explain why this question matters (e.g., to differentiate similar conditions).')),
                ('skin_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_questions', to='predictor.skincondition')),
            ],
        ),
    ]
