# Generated by Django 5.1.5 on 2026-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0020_remedy_approach_remedy_safety_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('home', 'Home'), ('medical', 'Medical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('directions', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('confidence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
