# Generated by Django 5.1.5 on 2026-01-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0021_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='category',
            field=models.CharField(choices=[('home', 'Home Remedy'), ('medical', 'Medical Treatment'), ('lifestyle', 'Lifestyle Change')], default='home', max_length=20),
        ),
    ]
