# Generated by Django 5.1.5 on 2026-01-03 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0022_remedy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='confidence',
            new_name='scientific_evidence',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='issue_name',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='treatment',
            name='approach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatment_images/'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='safety_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='skin_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.skincondition'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='traditional_evidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('home', 'Home')], max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
