# Generated by Django 5.1.5 on 2026-01-03 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0023_rename_confidence_treatment_scientific_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='approach',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='safety_level',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='traditional_evidence',
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
