# Generated by Django 5.1.5 on 2026-01-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0024_remove_treatment_approach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestylePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=255, unique=True)),
                ('diet_guidance', models.TextField()),
                ('skincare_guidance', models.TextField()),
                ('exercise_guidance', models.TextField()),
                ('habits_guidance', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
