# Generated by Django 5.1.5 on 2026-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0025_lifestyleplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100, unique=True)),
                ('diet', models.TextField()),
                ('skincare', models.TextField()),
                ('exercise', models.TextField()),
                ('sleep', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LifestylePlan',
        ),
    ]
