# Generated by Django 5.1.5 on 2025-10-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='license_docs/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('doctor', 'Doctor'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
