# Generated by Django 5.1.5 on 2025-10-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skinprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprogress',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='skinprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skinprogress',
            name='detection_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
