# Generated by Django 5.1.5 on 2025-12-02 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skinprogress_ai_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('itchiness', models.BooleanField(blank=True, null=True)),
                ('other_notes', models.TextField(blank=True)),
                ('multimodal_prediction', models.CharField(blank=True, max_length=128)),
                ('multimodal_confidence', models.FloatField(blank=True, null=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.skinprogress')),
            ],
        ),
    ]
