# Generated by Django 5.1.5 on 2026-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patientreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprogress',
            name='confidence_scores_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
