# Generated by Django 5.1.5 on 2026-01-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_government_id_patientreport_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
