# Generated by Django 5.1.5 on 2026-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
