# Generated by Django 5.1.5 on 2026-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_doctorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='gender',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
