# Generated by Django 5.1.5 on 2026-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_age_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinprogress',
            name='improvement_score',
        ),
        migrations.AddField(
            model_name='skinprogress',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinprogress',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skinprogress',
            name='confidence_scores_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='skinprogress',
            name='image',
            field=models.ImageField(upload_to='skin_images/'),
        ),
    ]
