# Generated by Django 5.1.5 on 2026-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_skinprogress_improvement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprogress',
            name='improvement_score',
            field=models.FloatField(default=0),
        ),
    ]
