# Generated by Django 5.1.5 on 2026-01-11 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_issues', models.JSONField(default=list)),
                ('confidence_scores', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ai_reports_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
