# Generated by Django 5.1.5 on 2026-01-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_myaireport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Review_Report_by_Doctor',
        ),
    ]
