# Generated by Django 5.1.5 on 2026-01-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_review_review_report_by_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprogress',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated_reports/'),
        ),
    ]
