# Generated by Django 5.1.5 on 2026-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_skinprogress_annotated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated_reports/'),
        ),
    ]
