# Generated by Django 5.1.5 on 2026-01-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_patientreport_annotated_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myaireport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='myaireport',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_reports/annotated_images/'),
        ),
        migrations.AddField(
            model_name='myaireport',
            name='skin_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to='users.skinprogress'),
        ),
        migrations.AddField(
            model_name='myaireport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='detected_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('followup', 'Follow-Up Needed')], default='pending', max_length=20),
        ),
    ]
