# Generated by Django 5.1.5 on 2026-01-12 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_myaireport_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaireport',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_reports/'),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='detected_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ai_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='skin_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.skinprogress'),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
