# Generated by Django 5.1.5 on 2026-01-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_myaireport_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaireport',
            name='skin_progress',
        ),
        migrations.AddField(
            model_name='myaireport',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myaireport',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='detected_issues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
