# Generated by Django 5.1.5 on 2026-01-12 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_myaireport_skin_progress_myaireport_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaireport',
            name='age',
        ),
        migrations.RemoveField(
            model_name='myaireport',
            name='gender',
        ),
        migrations.AddField(
            model_name='myaireport',
            name='confidence_scores_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='myaireport',
            name='skin_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to='users.skinprogress'),
        ),
        migrations.AddField(
            model_name='myaireport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_reports/annotated_images/'),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ai_reports_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('followup', 'Follow-Up Needed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='myaireport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ai_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
