# Generated by Django 5.1.5 on 2026-01-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_myaireport_age_remove_myaireport_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaireport',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myaireport',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
