# Generated by Django 5.1.5 on 2026-01-12 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_myaireport_age_myaireport_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaireport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_ai_reports_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
