# Generated by Django 5.1.5 on 2026-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_myaireport_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaireport',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
