# Generated by Django 5.2.4 on 2025-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.JSONField(default=list, null=True),
        ),
    ]
