# Generated by Django 5.2.4 on 2025-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_convert_answer_content_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
